# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cristian Schmitt Nieto´s Blog
email: blog@schmitt-nieto.com
description: Welcome to my blog, where you will find all kinds of information related to Azure, Azure Virtual Desktop and Azure Stack HCI.
github_username: schmittnieto
minimal_mistakes_skin: "dark"
logo: "/assets/img/logo.png"
masthead_title: "To Infinity and Azure 🦾"

# Search
search: true
lunr:
  search_within_pages: true

# Miscellaneous 
enable_copy_code_button: true
teaser: /assets/img/avatar-logo2.png

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: DE

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Cristian Schmitt Nieto"
  avatar : "/assets/img/avatar-csn.jpeg"
  bio    : "Azure Consultant with over 10 years of IT experience, sharing insights and solutions here 😊"
  location: "Frankfurt"
  links:
    - label: "schmitt-nieto.com"
      icon: "fas fa-fw fa-link"
      url: "https://schmitt-nieto.com/about"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/schmittnieto"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/cristian-schmitt-nieto/"     

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/schmittnieto"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/cristian-schmitt-nieto/"     

comments:
  provider: "disqus"
  disqus:
    shortname:  "schmittnieto"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: "google"
  google:
    tracking_id: "G-0JC8WREF2K"
#    anonymize_ip: true